fourpm/fourpm/Controllers/TeacherController.cs
using fourpm.Data;
using fourpm.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;

namespace fourpm.Controllers
{
    public class TeacherController : Controller
    {
        private readonly dbContext _context;
        public TeacherController(dbContext context)
        {
            _context = context;
        }
    
        public IActionResult Index() //action method
        {
            List<Teacher> modelData = _context.Teachers
                .OrderByDescending(x => x.Id)
                .ToList();
            return View(modelData); 


        }
        
        public IActionResult Create()  // httpget
        {
            Teacher modal=  new Teacher();  
            return View(modal); 
        }

        [HttpPost]  //action verbs
        public IActionResult Create(Teacher model)
        {
            _context.Teachers.Add(model);  
            _context.SaveChanges();
            return RedirectToAction("Index");   

        }

        public IActionResult Edit(int id)  //cont/action/id
        {
            var found = _context.Teachers.Find(id);
            return View(found);
        }

        [HttpPost]
        public IActionResult Edit(Teacher model)
        {
            var found = _context.Teachers.Find(model.Id);
            found.Name=model.Name;
            found.Email=model.Email;    
            found.Mobile=model.Mobile;  
            _context.Teachers.Update(found);    
            _context.SaveChanges(); 
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            var found = _context.Teachers.Find(id);
            return View(found);
        }

        [HttpPost]
        public IActionResult Delete(Teacher model)
        {
            var found = _context.Teachers.Find(model.Id);

            _context.Teachers.Remove(found);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

fourpm/fourpm/Views/Shared/Components/globalvotesViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using fourpm.Models;
namespace fourpm.Views.Shared.Components
{
    public class globalvotesViewComponent:ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            //any logic
            //for(int i=1; i<=10; i++)
            //{
            //    //do some thing
            //}

            // if condi

            //database communication
            //email

            List<voteresults> _model = new List<voteresults>();
            _model.Add(new voteresults() { party="Wadani", percentage=29 });
            _model.Add(new voteresults() { party = "Kulmiye", percentage = 20 });
            _model.Add(new voteresults() { party = "Ucid", percentage = 51 });


            return View("Default",_model);
        }
    }
}

fourpm/fourpm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - fourpm</title>
    
    <link href="~/css/mybundle.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/fourpm.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">fourpm</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teacher" asp-action="Index">Teacher</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - fourpm - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
@*    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/testing.js"></script>
    <script src="~/js/thirdfile.js"></script>*@
    <script src="~/js/mybundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

fourpm/fourpm/Views/Shared/_menu.cshtml
<table>
    <tr>
        <td><a href="/">Home</a></td>
        <td><a href="/home/layoutexample">Somaliland</a></td>
        <td><a href="/home/layoutexample2">Egypt</a></td>
        <td><a href="/">News</a></td>
    </tr>
</table>

fourpm/fourpm/Views/Shared/_newLayout.cshtml
<html>
<head>
    <title>New Layout</title>
</head>
<body>
    <table border="1" width="100%">
        <tr>
            <td>
                <h2>
                   @Html.Partial("_menu")
                </h2>
            </td>
        </tr>
        <tr>
            <td>
                @RenderBody()
            </td>
        </tr>
        <tr>
            <td>
                <h2>Footer Location</h2>
                @Html.Partial("_menu")
            </td>
        </tr>
    </table>

</body>
</html>

fourpm/fourpm/Views/Shared/_votes.cshtml
@using fourpm.Models
@model List<voteresults>
<center>
    <h3>Vote Result</h3>
    <ol>
        @foreach(var item in Model)
        {
            <li>@item.party @item.percentage.ToString()%</li>
        }

    </ol>
</center>