fourpm/fourpm/Controllers/xawaaladController.cs
using Microsoft.AspNetCore.Mvc;

namespace fourpm.Controllers
{
    public class xawaaladController : Controller
    {
        public IActionResult welcome()
        {
            return View();
        }

        public IActionResult Adeeg()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }
    }
}

fourpm/fourpm/Views/xawaalad/Adeeg.cshtml
<center>
    <h3>
        Faahfaahinta Adeegyada Baanka
    </h3>
</center>

<div style="background-color:pink; padding:20px;">
    <img src="~/imgone.png"  style="width:200px; height:200px;"/>
    <br />
    <ol>
        <li>Baanka</li>
        <li>Xawaalada</li>
        <li>Maalgalinta</li>
    </ol>
</div>

<br />
<a asp-controller="Xawaalad" asp-action="Welcome">Go Back</a>

fourpm/fourpm/Views/xawaalad/Login.cshtml
<center>
    <h1>Login</h1>
    <input placeholder="Username"/>
    <input placeholder="Password"/>
    <button>Login</button>
</center>

fourpm/fourpm/Views/xawaalad/welcome.cshtml
<center>
    <h2>Kusoo Dhawoow Xawaalada Dahabshiil </h2>
</center>

<p>
    Dahabshiil waxaa la aasaasey 1995 kii.
    waxaa markii ugu horeysey lagu bilaabey 
    xawaalada dibada.
</p>

<br />
<h4>Adeegyada Xawaalada:</h4>
<ol>
    <li>Xawaalada Gudaha</li>
    <li>Xawaalada Dibada</li>
    <li>Adeega Baanka</li>
    <li>Maalgalinta</li>
</ol>

<div style="background-color:cyan; border:1px solid black;">
    <h3>Adeega Baanka:</h3>
    <ul>
        <li>Akoonada caadiga ah</li>
        <li>Akoonada keydka</li>
        <li>Akoonada Maalgashiga</li>
    </ul>


</div>

<a asp-controller="xawaalad" asp-action="adeeg">Click Here</a> si aad u hesho macluumaad dheeriya